language: go
go:
- "1.14"

script:
- make release

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: mtMwegigeKX0aZGDbXJz6SR5fQlOWsffZsai4HESVuNM7dwzel1Es/IEI1PYQTkXxX2Tkq3lrk7fyGpWNiZajNMkhqqVGxPE6rminAcHbrGLMxMnTVo8fuB8d7HtpbfYP1sLkB9p5fztxRUnAxe95pCpBEcLtYcdX5npF6SAKlFjOfm1jZLamBRSgJGm6ploKyDBYYOXBfRvMh3Omf5zA9/wY0M8ybmpYtbnAwoEX/hPstt+bzxe0rgQcweaXDNQ0b0VPrl+llDqUc8jklfJBkyPvmarlUCfQ6ajzf/0dFj27QZAHXxT6FFkxA71pHPbbk/61W5AKXRb9/VCazFQjh7XWkar52cfHBs8lQa4TTdmhJPHhJKSAO3T/ZznTa1oVBykzO8iohil5V7AAANOnoaXk1VNexmppzABTgchLE6lzr019x89ZjC+ZZpjJW09sNjtkx23H9cAWEfSnkvWVk3U/dtWt22PH90S4SZ8qX6gnrTDP2p9PsoEWYlwbKQXiyOw3Mh2h8QkLvXWzJAOnJiw779FQyx1Cf2AmnA46csoqQP06GM5tJyybUSGI7U/5eTcFZfqrYPB2rMKEEAtM1AYvwt6EuUADBiJHSHbAF/unCk9toqdBhBZwiMeeKfdpfGkudILGZOJwRIDeVcaNSYlUB18rqwaM7ue7FX/oUo=
  file_glob: true
  file: dist/ssh-aliases_*
  on:
    tags: true
